### ISSUE TITLE
Iniciando traduccion capitulo 21

### ISSUE THREAD

**Issue by gamba47** [victorhck/Aprende-Vim#12]
Hola, gracias por tomarte el trabajo en la edicion del documento, si te parece bien voy a tratar esta semana de traducir y pasarte el ch21_vimrc.md

Ya lo empece, pero no se como voy a estar de tiempos (estoy recien llegado de vacaciones y seguro algo me pasa)

Saludos! y perdon si este no es el medio.

**Comment by victorhck** [comment]
Hola!
Ok, Tranquilo, traduce a tu ritmo y espero tu Pull Request! ;)
Saludos

**Comment by victorhck** [comment]
Corregido y aceptado el PR.
Gracias.
