### ISSUE TITLE
"set hidden" Capítulo 2: Buffers, ventanas y pestañas

### ISSUE THREAD

**Issue by mdtrooper** [victorhck/Aprende-Vim#14]
Buenas, no se si el documento es una traducción 1 a 1 del manual que comentas al principio.

Pero bueno, si es asi, cierro el issue.

El texto:

```
Dentro del archivo, añade la siguiente línea:

set hidden
```

Me deja un poco frío porque no tengo idea de que significa hidden...quizá meter una pequeña explicación de que hace...he buscado y tampoco me he enterado bien de que hace.

**Comment by victorhck** [comment]
Sí es una traducción del manual. No hay añadidos de mi cosecha... Quizás puedes comentarlo en la guía original.
El comando lo que hace es permitir poder pasar a otro buffer (otra pestaña) sin necesidad haber guardado el buffer actual.

Si hidden está a off y tienes un buffer modificado sin guardar, si quieres pasar a otro buffer, antes te pedirá que guardes los cambios del buffer actual.
Con hidden a on, no te pedirá eso y podrás cambiar de buffer sin necesidad de guardar los cambios.

Saludos!

**Comment by mdtrooper** [comment]
Perfecto, gracia lo cierro...si quieres ponerle etiqueta de invalido o así, me parece bien.
